/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 boy.gltf --transform
Author: Artistic_side (https://sketchfab.com/leorehman333)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/free-boy-game-character-3e1a1c2046ad48f1b80bc0b573068113
Title: Free Boy Game Character
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/boy-transformed.glb')

  // Change the color of materials

  materials.material_4.color.set('#38240c'); // Hair and eyebrows (Dark brown)
  materials['Material.002'].color.set('#000000'); // Eyes (Pupils - Black)
  materials['Material.005'].color.set('#1f6399'); // Glasses (Dark blue)
  materials['Material.003'].color.set('#e20707'); // Mouth (Red)
  materials.material.color.set('#ffddb3'); // Skin (Light skin tone)
  materials.white.color.set('#ffffff'); // Back of the eye, stripes in the shirt, and bottom of the shoe (White)
  materials.material_2.color.set('#ffddb3'); // Ears from inside and cheeks (Light beige)
  materials['Material.001'].color.set('#000000'); // Shoes (Black)
  materials['Material.006'].color.set('#0698d1'); // Shirt (Light gray)
  materials['Material.007'].color.set('#3b3b3b'); // Shorts (Dark gray)
  materials.material_10.color.set('#3b3b3b'); // Stripe in the shorts (Dark gray)
  

  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.GLTF_created_0_rootJoint} />
      <mesh geometry={nodes.Object_17.geometry} material={materials.material_4} position={[0, 0.715, 0]} scale={0.257} />
      <mesh geometry={nodes.Object_19.geometry} material={materials['Material.002']} position={[0, 0.715, 0.006]} scale={0.257} />
      <mesh geometry={nodes.Object_21.geometry} material={materials['Material.005']} position={[-0.006, 0.683, 0.168]} rotation={[Math.PI / 2, 0, 0]} scale={0.031} />
      <mesh geometry={nodes.Object_25.geometry} material={materials['Material.003']} position={[0, 0.593, 0.152]} rotation={[1.863, 0, 0]} scale={0.01} />
      <skinnedMesh geometry={nodes.Object_7.geometry} material={materials.material} skeleton={nodes.Object_7.skeleton} />
      <skinnedMesh geometry={nodes.Object_12.geometry} material={materials.material} skeleton={nodes.Object_12.skeleton} />
      <skinnedMesh geometry={nodes.Object_8.geometry} material={materials.white} skeleton={nodes.Object_8.skeleton} />
      <skinnedMesh geometry={nodes.Object_13.geometry} material={materials.white} skeleton={nodes.Object_13.skeleton} />
      <skinnedMesh geometry={nodes.Object_9.geometry} material={materials.material_2} skeleton={nodes.Object_9.skeleton} />
      <skinnedMesh geometry={nodes.Object_14.geometry} material={materials.material_2} skeleton={nodes.Object_14.skeleton} />
      <skinnedMesh geometry={nodes.Object_10.geometry} material={materials['Material.001']} skeleton={nodes.Object_10.skeleton} />
      <skinnedMesh geometry={nodes.Object_15.geometry} material={materials['Material.001']} skeleton={nodes.Object_15.skeleton} />
      <skinnedMesh geometry={nodes.Object_27.geometry} material={materials['Material.006']} skeleton={nodes.Object_27.skeleton} />
      <skinnedMesh geometry={nodes.Object_30.geometry} material={materials['Material.006']} skeleton={nodes.Object_30.skeleton} />
      <skinnedMesh geometry={nodes.Object_28.geometry} material={materials.white} skeleton={nodes.Object_28.skeleton} />
      <skinnedMesh geometry={nodes.Object_31.geometry} material={materials.white} skeleton={nodes.Object_31.skeleton} />
      <skinnedMesh geometry={nodes.Object_33.geometry} material={materials['Material.007']} skeleton={nodes.Object_33.skeleton} />
      <skinnedMesh geometry={nodes.Object_36.geometry} material={materials['Material.007']} skeleton={nodes.Object_36.skeleton} />
      <skinnedMesh geometry={nodes.Object_34.geometry} material={materials.material_10} skeleton={nodes.Object_34.skeleton} />
      <skinnedMesh geometry={nodes.Object_37.geometry} material={materials.material_10} skeleton={nodes.Object_37.skeleton} />
    </group>
  )
}

useGLTF.preload('/boy-transformed.glb')
