/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 model.gltf --transform
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei';
import { MeshStandardMaterial } from 'three';

export default function Model(props) {
  const { nodes, materials } = useGLTF('/MyAvatarV2-transformed.glb')

  // Define the desired colors
  const bodyColor = 'rgb(199, 161, 125)'; 

  // Create new materials with the desired colors
  const headMaterial = new MeshStandardMaterial({ color: bodyColor });

  // Assign the new materials to the corresponding meshes
  materials.Wolf3D_Skin = headMaterial;

  return (
    <>
    <PerspectiveCamera position={[0, 0, 0]} />
    <group {...props} scale={2.7} position={[0.5, -2.5, 0]} rotation={[0.3, -0.6, 0]} dispose={null}>
      <mesh geometry={nodes.EyeLeft.geometry} material={materials.Wolf3D_Eye} />
      <mesh geometry={nodes.Wolf3D_Head.geometry} material={materials.Wolf3D_Skin} />
      <mesh geometry={nodes.Wolf3D_Teeth.geometry} material={materials.Wolf3D_Teeth} />
      <mesh geometry={nodes.Wolf3D_Body.geometry} material={materials.Wolf3D_Body} />
      <mesh geometry={nodes.Wolf3D_Outfit_Bottom.geometry} material={materials.Wolf3D_Outfit_Bottom} />
      <mesh geometry={nodes.Wolf3D_Outfit_Footwear.geometry} material={materials.Wolf3D_Outfit_Footwear} />
      <mesh geometry={nodes.Wolf3D_Outfit_Top.geometry} material={materials.Wolf3D_Outfit_Top} />
      <mesh geometry={nodes.Wolf3D_Hair.geometry} material={materials.Wolf3D_Hair} />
    </group>
    </>
  )
}

useGLTF.preload('/MyAvatarV2-transformed.glb')
