/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 modelDraco.gltf --transform
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';
import { MeshStandardMaterial } from 'three';

export default function Model(props) {
  const { nodes } = useGLTF('/MyAvatar-transformed.glb');

  // Define the desired colors
  const bodyColor = '#c29164'; 
  const bottomColor = '#17191b'; // Green
  const topColor = '#09153a'; // Green
  const footwearColor = '#000000'; // Blue

  // Create new materials with the desired colors
  const bodyMaterial = new MeshStandardMaterial({ color: bodyColor });
  const bottomMaterial = new MeshStandardMaterial({ color: bottomColor });
  const topMaterial = new MeshStandardMaterial({ color: topColor });
  const footwearMaterial = new MeshStandardMaterial({ color: footwearColor });
  const headMaterial = new MeshStandardMaterial({ color: bodyColor });

  // Assign the new materials to the corresponding meshes
  nodes.Wolf3D_Body.material = bodyMaterial;
  nodes.Wolf3D_Outfit_Bottom.material = bottomMaterial;
  nodes.Wolf3D_Outfit_Top.material= topMaterial;
  nodes.Wolf3D_Outfit_Footwear.material = footwearMaterial;
  nodes.Wolf3D_Head.material = headMaterial;

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.EyeLeft.geometry} material={nodes.EyeLeft.material} />
      <mesh geometry={nodes.Wolf3D_Head.geometry} material={nodes.Wolf3D_Head.material} />
      <mesh geometry={nodes.Wolf3D_Teeth.geometry} material={nodes.Wolf3D_Teeth.material} />
      <mesh geometry={nodes.Wolf3D_Body.geometry} material={bodyMaterial} />
      <mesh geometry={nodes.Wolf3D_Outfit_Bottom.geometry} material={bottomMaterial} />
      <mesh geometry={nodes.Wolf3D_Outfit_Footwear.geometry} material={footwearMaterial} />
      <mesh geometry={nodes.Wolf3D_Outfit_Top.geometry} material={nodes.Wolf3D_Outfit_Top.material} />
      <mesh geometry={nodes.Wolf3D_Hair.geometry} material={nodes.Wolf3D_Hair.material} />
    </group>
  );
}

useGLTF.preload('/MyAvatar-transformed.glb');

