/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 computerDesign.gltf --transform
Author: Diego G. (https://sketchfab.com/empty_mirror)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/diseno-3d-web-development-resource-70f8d9e0f9924450888232a7a6afa02d
Title: Diseño 3D - Web Development Resource
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/computerDesign-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube002_Maceta_0.geometry} material={materials.PaletteMaterial001} position={[-0.272, -0.026, -0.025]} rotation={[0, 0.466, 0]} scale={0.08} />
    </group>
  )
}

useGLTF.preload('/computerDesign-transformed.glb')
